[typescript]
recommended = true

[javascript]
recommended = true

[react]
recommended = true

[rules]
# Базовые правила
no-console = "error"
no-debugger = "error"
no-duplicate-imports = "error"

# Настраиваем правило для неиспользуемых переменных
no-unused-vars = "warn"

# Другие полезные правила
prefer-const = "warn"
no-var = "warn"
no-let = "warn"
no-const = "warn"
no-this = "warn"
no-return-await = "warn"
no-await-in-loop = "warn"
no-array-constructor = "warn"
no-new-object = "warn"
no-new-wrappers = "warn"
no-param-reassign = "warn"
no-prototype-builtins = "warn"
no-redeclare = "warn"
no-self-assign = "warn"
no-unused-expressions = "warn"
no-useless-call = "warn"
no-useless-computed-key = "warn"
no-useless-concat = "warn"
no-useless-constructor = "warn"
no-useless-escape = "warn"
no-useless-rename = "warn"
no-useless-return = "warn"
no-void = "warn"
no-with = "warn"
prefer-arrow-callback = "warn"
prefer-destructuring = "warn"
prefer-numeric-literals = "warn"
prefer-object-spread = "warn"
prefer-promise-reject-errors = "warn"
prefer-rest-params = "warn"
prefer-spread = "warn"
prefer-template = "warn"

[ignore]
"dist/**" = true
"build/**" = true
"node_modules/**" = true